package com.isaev.currency.network

import com.google.gson.GsonBuilder
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

object Repository {
    private const val BASE_URL = "https://www.cbr-xml-daily.ru/"

    private val gson = GsonBuilder().create()

    private val retrofit = Retrofit
        .Builder()
        .baseUrl(BASE_URL)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .build()
        .create(ApiService::class.java)

    suspend fun getCurrency(): Currency {
        val data = retrofit.getCurrency()
        val valute = data.Valute

        return Currency(
            data.Date,
            data.PreviousDate,
            data.PreviousURL,
            data.Timestamp,
            listOf(
                VLT(
                    valute.AUD.ID,
                    valute.AUD.NumCode,
                    valute.AUD.CharCode,
                    valute.AUD.Nominal,
                    valute.AUD.Name,
                    valute.AUD.Value,
                    valute.AUD.Previous
                ),
                VLT(
                    valute.AZN.ID,
                    valute.AZN.NumCode,
                    valute.AZN.CharCode,
                    valute.AZN.Nominal,
                    valute.AZN.Name,
                    valute.AZN.Value,
                    valute.AZN.Previous
                ),
                VLT(
                    valute.GBP.ID,
                    valute.GBP.NumCode,
                    valute.GBP.CharCode,
                    valute.GBP.Nominal,
                    valute.GBP.Name,
                    valute.GBP.Value,
                    valute.GBP.Previous
                ),
                VLT(
                    valute.AMD.ID,
                    valute.AMD.NumCode,
                    valute.AMD.CharCode,
                    valute.AMD.Nominal,
                    valute.AMD.Name,
                    valute.AMD.Value,
                    valute.AMD.Previous
                ),
                VLT(
                    valute.BYN.ID,
                    valute.BYN.NumCode,
                    valute.BYN.CharCode,
                    valute.BYN.Nominal,
                    valute.BYN.Name,
                    valute.BYN.Value,
                    valute.BYN.Previous
                ),
                VLT(
                    valute.BGN.ID,
                    valute.BGN.NumCode,
                    valute.BGN.CharCode,
                    valute.BGN.Nominal,
                    valute.BGN.Name,
                    valute.BGN.Value,
                    valute.BGN.Previous
                ),
                VLT(
                    valute.BRL.ID,
                    valute.BRL.NumCode,
                    valute.BRL.CharCode,
                    valute.BRL.Nominal,
                    valute.BRL.Name,
                    valute.BRL.Value,
                    valute.BRL.Previous
                ),
                VLT(
                    valute.HUF.ID,
                    valute.HUF.NumCode,
                    valute.HUF.CharCode,
                    valute.HUF.Nominal,
                    valute.HUF.Name,
                    valute.HUF.Value,
                    valute.HUF.Previous
                ),
                VLT(
                    valute.VND.ID,
                    valute.VND.NumCode,
                    valute.VND.CharCode,
                    valute.VND.Nominal,
                    valute.VND.Name,
                    valute.VND.Value,
                    valute.VND.Previous
                ),
                VLT(
                    valute.HKD.ID,
                    valute.HKD.NumCode,
                    valute.HKD.CharCode,
                    valute.HKD.Nominal,
                    valute.HKD.Name,
                    valute.HKD.Value,
                    valute.HKD.Previous
                ),
                VLT(
                    valute.GEL.ID,
                    valute.GEL.NumCode,
                    valute.GEL.CharCode,
                    valute.GEL.Nominal,
                    valute.GEL.Name,
                    valute.GEL.Value,
                    valute.GEL.Previous
                ),
                VLT(
                    valute.DKK.ID,
                    valute.DKK.NumCode,
                    valute.DKK.CharCode,
                    valute.DKK.Nominal,
                    valute.DKK.Name,
                    valute.DKK.Value,
                    valute.DKK.Previous
                ),
                VLT(
                    valute.AED.ID,
                    valute.AED.NumCode,
                    valute.AED.CharCode,
                    valute.AED.Nominal,
                    valute.AED.Name,
                    valute.AED.Value,
                    valute.AED.Previous
                ),
                VLT(
                    valute.USD.ID,
                    valute.USD.NumCode,
                    valute.USD.CharCode,
                    valute.USD.Nominal,
                    valute.USD.Name,
                    valute.USD.Value,
                    valute.USD.Previous
                ),
                VLT(
                    valute.EUR.ID,
                    valute.EUR.NumCode,
                    valute.EUR.CharCode,
                    valute.EUR.Nominal,
                    valute.EUR.Name,
                    valute.EUR.Value,
                    valute.EUR.Previous
                ),
                VLT(
                    valute.EGP.ID,
                    valute.EGP.NumCode,
                    valute.EGP.CharCode,
                    valute.EGP.Nominal,
                    valute.EGP.Name,
                    valute.EGP.Value,
                    valute.EGP.Previous
                ),
                VLT(
                    valute.INR.ID,
                    valute.INR.NumCode,
                    valute.INR.CharCode,
                    valute.INR.Nominal,
                    valute.INR.Name,
                    valute.INR.Value,
                    valute.INR.Previous
                ),
                VLT(
                    valute.IDR.ID,
                    valute.IDR.NumCode,
                    valute.IDR.CharCode,
                    valute.IDR.Nominal,
                    valute.IDR.Name,
                    valute.IDR.Value,
                    valute.IDR.Previous
                ),
                VLT(
                    valute.KZT.ID,
                    valute.KZT.NumCode,
                    valute.KZT.CharCode,
                    valute.KZT.Nominal,
                    valute.KZT.Name,
                    valute.KZT.Value,
                    valute.KZT.Previous
                ),
                VLT(
                    valute.CAD.ID,
                    valute.CAD.NumCode,
                    valute.CAD.CharCode,
                    valute.CAD.Nominal,
                    valute.CAD.Name,
                    valute.CAD.Value,
                    valute.CAD.Previous
                ),
                VLT(
                    valute.QAR.ID,
                    valute.QAR.NumCode,
                    valute.QAR.CharCode,
                    valute.QAR.Nominal,
                    valute.QAR.Name,
                    valute.QAR.Value,
                    valute.QAR.Previous
                ),
                VLT(
                    valute.KGS.ID,
                    valute.KGS.NumCode,
                    valute.KGS.CharCode,
                    valute.KGS.Nominal,
                    valute.KGS.Name,
                    valute.KGS.Value,
                    valute.KGS.Previous
                ),
                VLT(
                    valute.CNY.ID,
                    valute.CNY.NumCode,
                    valute.CNY.CharCode,
                    valute.CNY.Nominal,
                    valute.CNY.Name,
                    valute.CNY.Value,
                    valute.CNY.Previous
                ),
                VLT(
                    valute.MDL.ID,
                    valute.MDL.NumCode,
                    valute.MDL.CharCode,
                    valute.MDL.Nominal,
                    valute.MDL.Name,
                    valute.MDL.Value,
                    valute.MDL.Previous
                ),
                VLT(
                    valute.NZD.ID,
                    valute.NZD.NumCode,
                    valute.NZD.CharCode,
                    valute.NZD.Nominal,
                    valute.NZD.Name,
                    valute.NZD.Value,
                    valute.NZD.Previous
                ),
                VLT(
                    valute.NOK.ID,
                    valute.NOK.NumCode,
                    valute.NOK.CharCode,
                    valute.NOK.Nominal,
                    valute.NOK.Name,
                    valute.NOK.Value,
                    valute.NOK.Previous
                ),
                VLT(
                    valute.PLN.ID,
                    valute.PLN.NumCode,
                    valute.PLN.CharCode,
                    valute.PLN.Nominal,
                    valute.PLN.Name,
                    valute.PLN.Value,
                    valute.PLN.Previous
                ),
                VLT(
                    valute.RON.ID,
                    valute.RON.NumCode,
                    valute.RON.CharCode,
                    valute.RON.Nominal,
                    valute.RON.Name,
                    valute.RON.Value,
                    valute.RON.Previous
                ),
                VLT(
                    valute.XDR.ID,
                    valute.XDR.NumCode,
                    valute.XDR.CharCode,
                    valute.XDR.Nominal,
                    valute.XDR.Name,
                    valute.XDR.Value,
                    valute.XDR.Previous
                ),
                VLT(
                    valute.SGD.ID,
                    valute.SGD.NumCode,
                    valute.SGD.CharCode,
                    valute.SGD.Nominal,
                    valute.SGD.Name,
                    valute.SGD.Value,
                    valute.SGD.Previous
                ),
                VLT(
                    valute.TJS.ID,
                    valute.TJS.NumCode,
                    valute.TJS.CharCode,
                    valute.TJS.Nominal,
                    valute.TJS.Name,
                    valute.TJS.Value,
                    valute.TJS.Previous
                ),
                VLT(
                    valute.THB.ID,
                    valute.THB.NumCode,
                    valute.THB.CharCode,
                    valute.THB.Nominal,
                    valute.THB.Name,
                    valute.THB.Value,
                    valute.THB.Previous
                ),
                VLT(
                    valute.TRY.ID,
                    valute.TRY.NumCode,
                    valute.TRY.CharCode,
                    valute.TRY.Nominal,
                    valute.TRY.Name,
                    valute.TRY.Value,
                    valute.TRY.Previous
                ),
                VLT(
                    valute.TMT.ID,
                    valute.TMT.NumCode,
                    valute.TMT.CharCode,
                    valute.TMT.Nominal,
                    valute.TMT.Name,
                    valute.TMT.Value,
                    valute.TMT.Previous
                ),
                VLT(
                    valute.UZS.ID,
                    valute.UZS.NumCode,
                    valute.UZS.CharCode,
                    valute.UZS.Nominal,
                    valute.UZS.Name,
                    valute.UZS.Value,
                    valute.UZS.Previous
                ),
                VLT(
                    valute.UAH.ID,
                    valute.UAH.NumCode,
                    valute.UAH.CharCode,
                    valute.UAH.Nominal,
                    valute.UAH.Name,
                    valute.UAH.Value,
                    valute.UAH.Previous
                ),
                VLT(
                    valute.CZK.ID,
                    valute.CZK.NumCode,
                    valute.CZK.CharCode,
                    valute.CZK.Nominal,
                    valute.CZK.Name,
                    valute.CZK.Value,
                    valute.CZK.Previous
                ),
                VLT(
                    valute.SEK.ID,
                    valute.SEK.NumCode,
                    valute.SEK.CharCode,
                    valute.SEK.Nominal,
                    valute.SEK.Name,
                    valute.SEK.Value,
                    valute.SEK.Previous
                ),
                VLT(
                    valute.CHF.ID,
                    valute.CHF.NumCode,
                    valute.CHF.CharCode,
                    valute.CHF.Nominal,
                    valute.CHF.Name,
                    valute.CHF.Value,
                    valute.CHF.Previous
                ),
                VLT(
                    valute.RSD.ID,
                    valute.RSD.NumCode,
                    valute.RSD.CharCode,
                    valute.RSD.Nominal,
                    valute.RSD.Name,
                    valute.RSD.Value,
                    valute.RSD.Previous
                ),
                VLT(
                    valute.KRW.ID,
                    valute.KRW.NumCode,
                    valute.KRW.CharCode,
                    valute.KRW.Nominal,
                    valute.KRW.Name,
                    valute.KRW.Value,
                    valute.KRW.Previous
                ),
                VLT(
                    valute.JPY.ID,
                    valute.JPY.NumCode,
                    valute.JPY.CharCode,
                    valute.JPY.Nominal,
                    valute.JPY.Name,
                    valute.JPY.Value,
                    valute.JPY.Previous
                )
            )
        )
    }
}